export const nfthardcode = [
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
  {
    name: "Lonely Space CLub",
    number: 1234,
    price: 0.003,
    ticker: "ETH",
    blockchain: "Ethereum",
  },
];
